--(1)
SELECT DEPARTMENT_NAME"학과명",CATEGORY"계열" FROM TB_DEPARTMENT;

SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT;
--(2)
SELECT DEPARTMENT_NAME||'의 정원은'||' '|| CAPACITY ||'명 입니다' "학과별 정원" FROM TB_DEPARTMENT;

--(3)제외 JOIN배우고함
SELECT STUDENT_NAME,DECODE(SUBSTR(STUDENT_SSN,8,1),'2','여자'),ABSENCE_YN FROM TB_STUDENT 
WHERE ABSENCE_YN='Y' AND DECODE(SUBSTR(STUDENT_SSN,8,1),'2','여자');




