--1. 학생이름과 주소지를 표시하시오. 단,출력 헤더는 "학생이름","주소지"로 하고, 정렬은 이름으로 오름차순 표시하도록 한다.
SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지 FROM TB_STUDENT;

--2. 휴학중인 학생들의 이름과 주민번호를 나이가 적은 순서로 화면에 출력하시오.
SELECT STUDENT_NAME, STUDENT_SSN FROM TB_STUDENT WHERE ABSENCE_YN='Y' ORDER BY STUDENT_SSN DESC;

--3. 주소지가 강원도나 경기도인 학생들 중 1900년대 학번을 가진 학생들의 이름과 학번, 주소를 
--이름의 오름차순으로 화면에 출력하시오. 단, 출력헤더에는 "학생이름","학번","거주지주소"가 출력되도록 한다.
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS 거주지주소, STUDENT_SSN
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '강원%' OR STUDENT_ADDRESS LIKE '경기%')
AND SUBSTR(STUDENT_NO,1,2) BETWEEN '90' AND '99'
ORDER BY STUDENT_NAME ASC;

--4. 현재 법학과 교수중 가장 나이가 많은 사람부터 이름을 확인할수 있는 SQL문장을 작성하시요.
--(법학과의 '학과코드'는 학과테이블(TB_DEPARTMENT)을 조회해서 찾아내도록 하자)
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_DEPARTMENT JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN ASC;
     
--5. 2004년 2학기에 'C3118100' 과목을 수강한 학생들의 학점을 조회하려고 한다. 
--학점이 높은 학생부터 표시하고, 학점이 같으면 학번이 낮은 학생부터 표시하는 구문을 작성해보시오.
SELECT STUDENT_NO, TO_CHAR(POINT,99.99) POINT
FROM TB_STUDENT JOIN TB_GRADE USING(STUDENT_NO)
WHERE CLASS_NO = 'C3118100' AND SUBSTR(TERM_NO,1,6) LIKE '200402%'
ORDER BY POINT DESC, STUDENT_NO DESC;

--6. 학생번호,학생이름,학과이름을 학생이름으로 오름차순 정렬하여 출력하는 SQL문을 작성하시오.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

--7. 춘 기술대학교의 과목 이름과 과목의 학과 이름을 출력하는 SQL 문장을 작성하시오.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--8. 과목별 교수 이름을 찾으려고 한다. 과목 이름과 교수 이름을 출력하는 SQL문을 작성하시오.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS JOIN TB_CLASS_PROFESSOR USING(CLASS_NO) JOIN TB_PROFESSOR USING(PROFESSOR_NO);
-->화면과 출력다름? 로우갯수는맞음

--9. 8번의 결과중 '인문사회'계열에 속한 교수이름을 찾으려고한다. 이에 해당하는 과목이름과 교수이름을 출력하는 SQL문을 작성하시오.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO) 
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO=D.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';
-->화면과 출력다름? 로우갯수는맞음

