--【문항 5】 김유신 고객이 주문한 주문제품과 수량을 검색하시오.
--          - ANSI 구문과 ORACLE 구문 모두 작성하시오.

--ANSI
SELECT ORDER_PRODUCT, COUNT
FROM MEMBER
JOIN ORDERS ON(ID = ORDER_ID)
WHERE NAME = '김유신';
--ORACLE
SELECT ORDER_PRODUCT, COUNT
FROM MEMBER, ORDERS
WHERE MEMBER.ID = ORDERS.ORDER_ID AND NAME = '김유신';